config-version = 2

# persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]

after-startup-command = [
  'exec-and-forget borders active_color=0xff89b4fa inactive_color=0xff45475a width=5.0'
]

on-focus-changed = [
  "exec-and-forget osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-index-jsx\"'",
]

exec-on-workspace-change = [
  '/bin/zsh',
  '-c',
  '/usr/bin/osascript -e "tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-index-jsx\""',
]

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top = [
  { monitor."built-in" = 10 },
  { monitor."main" = 49 },
  49
]
outer.right =      10

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'secondary'
3 = 'main'
4 = 'main'
5 = 'main'
6 = 'secondary'
7 = 'secondary'
8 = 'secondary'
9 = 'secondary'

[mode.main.binding]
    cmd-enter = 'exec-and-forget /Applications/WezTerm.app/Contents/MacOS/wezterm start --always-new-process'

    # i3 wraps focus by default
    cmd-left  =         'focus --boundaries-action wrap-around-the-workspace left'
    cmd-down  =         'focus --boundaries-action wrap-around-the-workspace down'
    cmd-up    =         'focus --boundaries-action wrap-around-the-workspace up'
    cmd-right = 'focus --boundaries-action wrap-around-the-workspace right'

    cmd-shift-left  = 'move left'
    cmd-shift-down  = 'move down'
    cmd-shift-up    = 'move up'
    cmd-shift-right = 'move right'

    cmd-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    # Not supported, because this command is redundant in AeroSpace mental model.
    # See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
    #cmd-space = 'focus toggle_tiling_floating'

    # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
    # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
    # cmd-a = 'focus parent'

    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'
    cmd-6 = 'workspace 6'
    cmd-7 = 'workspace 7'
    cmd-8 = 'workspace 8'
    cmd-9 = 'workspace 9'
    cmd-0 = 'workspace 10'

    cmd-shift-1 = 'move-node-to-workspace 1'
    cmd-shift-2 = 'move-node-to-workspace 2'
    cmd-shift-3 = 'move-node-to-workspace 3'
    cmd-shift-4 = 'move-node-to-workspace 4'
    cmd-shift-5 = 'move-node-to-workspace 5'
    cmd-shift-6 = 'move-node-to-workspace 6'
    cmd-shift-7 = 'move-node-to-workspace 7'
    cmd-shift-8 = 'move-node-to-workspace 8'
    cmd-shift-9 = 'move-node-to-workspace 9'
    cmd-shift-0 = 'move-node-to-workspace 10'

    cmd-shift-c = 'reload-config'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'
