;;; batppuccin-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from batppuccin.el

(autoload 'batppuccin-with-colors "batppuccin" "\
Bind all palette colors for the current Batppuccin theme and evaluate BODY.
Inside BODY, each palette color is available as a local variable,
e.g. `bat-blue', `bat-base', etc.

Example:
  (batppuccin-with-colors
    (set-face-attribute \\='some-face nil :foreground bat-blue))

(fn &rest BODY)" nil t)
(function-put 'batppuccin-with-colors 'lisp-indent-function 0)
(autoload 'batppuccin-reload "batppuccin" "\
Reload the current Batppuccin theme.
Useful after changing `batppuccin-override-colors-alist' or
`batppuccin-scale-headings' without having to call `load-theme'
manually." t)
(autoload 'batppuccin-select "batppuccin" "\
Select and load a Batppuccin theme variant interactively." t)
(register-definition-prefixes "batppuccin" '("batppuccin-"))


;;; Generated autoloads from batppuccin-frappe-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "batppuccin-frappe-theme" '("batppuccin-frappe"))


;;; Generated autoloads from batppuccin-latte-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "batppuccin-latte-theme" '("batppuccin-latte"))


;;; Generated autoloads from batppuccin-macchiato-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "batppuccin-macchiato-theme" '("batppuccin-macchiato"))


;;; Generated autoloads from batppuccin-mocha-theme.el

(and load-file-name (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "batppuccin-mocha-theme" '("batppuccin-mocha"))

;;; End of scraped data

(provide 'batppuccin-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; batppuccin-autoloads.el ends here
