[servers.Libera]
nickname = "kzzzl"
nick_password_command = "source ~/.secrets && /opt/homebrew/bin/bw get password libera"
server = "irc.libera.chat"
channels = ["#libera", "#macdev"]

[servers.OFTC]
server = "irc.oftc.net"
nick_password_command = "source ~/.secrets && /opt/homebrew/bin/bw get password oftc"
nickname = "kzzzl"
channels = ["#asahi", "#asahi-alt", "#asahi-re"]
